(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb ball4 ball3 ball2 ball1 left right)
   (:init (room rooma)
          (room roomb)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (at ball2 rooma)
          (at ball1 rooma)
          (gripper left))
   (:goal (and 
               (at ball2 roomb)
               (at ball1 roomb))))